msm_kernel_la.bzl: Workaround frozen list bazel error
When compiling we get:
msm-kernel/msm_kernel_la.bzl", line 479, column 25, in define_msm_la
                in_tree_module_list += vendor_dlkm_module_unprotected_list
Error: trying to mutate a frozen list value

However, the vendor_dlkm_module_unprotected_list is empty for the
`neo_la` target and therefore we can get around this error since we can
simply bypass this concatenation if the unprotected list is empty, which
arguably, makes sense regardless.

Change-Id: I43079ba902483f67e291a38b6a55397a62faa6b6
Signed-off-by: Auditya Bhattaram <quic_audityab@quicinc.com>